#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math
from dnslib import DNSRecord, DNSHeader, RR, QTYPE, A

zone = open('configs/example.com.zone', 'r')
zoneStr = zone.read()

class Server:
    def __init__(self, root_ip, domain, port):
        self.root_ip = root_ip
        self.domain = domain
        self.log(domain)

        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(("0.0.0.0", port))
        self.port = self.socket.getsockname()[1]

        self.log("Bound to port %d" % self.port)

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def send(self, addr, message):
        self.log("Sending message:\n%s" % message)
        self.socket.sendto(message.pack(), addr)
        
    def getResponse(self, request):
        question = request.get_q()
        qname = question.qname
        response = request.reply()
        
        for rr in RR.fromZone(zoneStr):
            if (rr.rname == qname) & (rr.rtype != 6) & (rr.rtype != 2):
                response.add_answer(rr)
                if (rr.rtype == 5):
                    qname2 = rr.rdata.toZone()
                    for rr2 in RR.fromZone(zoneStr):
                        if rr2.rname == qname2:
                            response.add_answer(rr2)
            if (rr.rname == 'example.com') & (rr.rtype == 2): response.add_auth(rr)
        
        return response

    def recv(self, socket):
        data, addr = socket.recvfrom(65535)

        # Unpack the DNS request
        request = DNSRecord.parse(data)
        self.log("Received message:\n%s" % request)

        response = self.getResponse(request)
        
        self.send(addr, response)

    def run(self):
        seq = 0
        while True:
            socks = select.select([self.socket], [], [], 0.1)[0]
            for conn in socks:
                self.recv(conn)

        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('root_ip', type=str, help="The IP address of the root server")
    parser.add_argument('zone', type=str, help="The zone file for this server")
    parser.add_argument('--port', type=int, help="The port this server should bind to", default=0)
    args = parser.parse_args()
    sender = Server(args.root_ip, args.zone, args.port)
    sender.run()
