#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math
from dnslib import DNSRecord, DNSHeader, RR, QTYPE, A

class Server:
    def __init__(self, root_ip, domain, port):
        self.root_ip = root_ip
        self.domain = domain
        self.log(domain)

        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(("0.0.0.0", port))
        self.port = self.socket.getsockname()[1]

        self.log("Bound to port %d" % self.port)

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def send(self, addr, message):
        self.log("Sending message:\n%s" % message)
        self.socket.sendto(message.pack(), addr)
        
    # Gets a response from the local authoritative zone
    def get_local_res(self, response):
        zoneStr = open('configs/example.com.zone', 'r').read()
        
        question = response.get_q()
        qname = question.qname
        qtype = question.qtype
        
        # handles NS question type
        if qtype == 2:
            for rr in RR.fromZone(zoneStr):
                # adds matching answer if NS
                if (rr.rname == qname) & (rr.rtype == 2):
                    response.add_answer(rr)
                    
                    qname2 = rr.rdata.toZone()
                    for rr2 in RR.fromZone(zoneStr):
                        if rr2.rname == qname2:
                            response.add_ar(rr2)
             
            # sets status to NXDOMAIN if no auth
            if response.header.a == 0: response.header.set_rcode(3)
            return response
        
        # handles other question types
        for rr in RR.fromZone(zoneStr):
            # adds matching answer if not SOA or NS
            if (rr.rname == qname) & (rr.rtype != 6) & (rr.rtype != 2):
                response.add_answer(rr)
                
                # adds additional answers if rr is CNAME
                if (rr.rtype == 5):
                    qname2 = rr.rdata.toZone()
                    for rr2 in RR.fromZone(zoneStr):
                        if rr2.rname == qname2:
                            response.add_answer(rr2)
            
            # adds authority section, should probably un-hard-code
            if (rr.rname == 'example.com') & (rr.rtype == 2): response.add_auth(rr)
            
        #TODO: Search cached responses before marking NXDOMAIN
        
        # sets status to NXDOMAIN if no answers
        if response.header.a == 0: response.header.set_rcode(3)
        return response
    
    # Queries other DNS servers to get response
    def get_ext_res(self, data, qtype):
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        # right ip and port???
        sock.bind(("0.0.0.0", 60053))
        sock.sendto(data, (self.root_ip, 60053))
        ext_data, _ = sock.recvfrom(65535)
        response = DNSRecord.parse(ext_data)
        
        # Returns immediately if type is NS or status is NXDOMAIN
        if (qtype == 2) | (response.header.rcode == 3):
            return response
        
        # Recursively searches for answer
        while True:
            new_ip = str(response.ar[0].rdata)
            sock.sendto(data, (new_ip, 60053))
            ext_data, _ = sock.recvfrom(65535)
            response = DNSRecord.parse(ext_data)
            
            if response.header.a > 0: return response
            
        #TODO: Cache responses, clear after TTL (time to live)

    def recv(self, socket):
        data, addr = socket.recvfrom(65535)

        # Unpack the DNS request
        request = DNSRecord.parse(data)
        self.log("Received message:\n%s" % request)
        
        #TODO: Run multiple of these in parallel, figure out what bailiwick is

        response = request.reply()
        local_res = self.get_local_res(response)
        # If answer found locally, send response
        if local_res.header.rcode != 3:
            # set authoritative bit
            local_res.header.set_aa(1)
            self.send(addr, local_res)
        else:
            # If answer found externally, send response
            ext_res = self.get_ext_res(data, response.get_q().qtype)
            if ext_res.header.rcode != 3:
                # unset authoritative bit
                ext_res.header.set_aa(0)
                # set recursion available bit
                ext_res.header.set_ra(1)
                # unset truncation bit
                ext_res.header.set_tc(0)
                self.send(addr, ext_res)
            else:
                # If no answer found, send NXDOMAIN response
                self.send(addr, local_res)

    def run(self):
        seq = 0
        while True:
            socks = select.select([self.socket], [], [], 0.1)[0]
            
            #TODO: Figure out how to run in parallel from here?
            
            for conn in socks:
                self.recv(conn)

        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('root_ip', type=str, help="The IP address of the root server")
    parser.add_argument('zone', type=str, help="The zone file for this server")
    parser.add_argument('--port', type=int, help="The port this server should bind to", default=0)
    args = parser.parse_args()
    sender = Server(args.root_ip, args.zone, args.port)
    sender.run()
